"""Independent source-health alert policy, persistence, rendering, and SMTP.

This module is the compatibility surface for everything that already imports
from ``watcher.health_alerts``. The implementation lives in focused modules:

* :mod:`watcher.health.models` -- alert types, severities, and the alert
  dataclasses.
* :mod:`watcher.health.store` -- :class:`HealthAlertStore`.
* :mod:`watcher.health.policy` -- severity assignment, fallback evidence,
  repeated-flap deferral, systemic grouping, and digest selection.
* :mod:`watcher.health.rendering` -- alert, daily-summary, and digest text.
* :mod:`watcher.health.service` -- evaluation, delivery, and the SMTP boundary.

Patch implementations where they are defined rather than through this module:
re-exported names are bound here at import time, so replacing one of them here
does not change what the owning module calls.
"""

from __future__ import annotations

from watcher.health.models import (
    ALERT_BOTH_TIERS_UNAVAILABLE,
    ALERT_CONTINUED_FAILURE,
    ALERT_COVERAGE_REGRESSION,
    ALERT_DIRECT_SOURCE_DEGRADED,
    ALERT_FEED_STALE,
    ALERT_MINOR_DEGRADATION,
    ALERT_MINOR_RECOVERY,
    ALERT_NEW_FAILURE,
    ALERT_RECOVERY,
    ALERT_UNKNOWN_DIAGNOSTICS,
    DEFAULT_COOLDOWN_HOURS,
    DEFAULT_FEED_STALE_HOURS,
    DEFAULT_HOUR_UTC,
    DEFAULT_MODE,
    DEGRADATION_ALERT_TYPES,
    DIGEST_SEVERITIES,
    DIGEST_WINDOW_HOURS,
    FAILURE_ALERT_TYPES,
    FLAP_LOOKBACK_HOURS,
    FLAP_REPEAT_THRESHOLD,
    GITHUB_EVIDENCE_HORIZON_DAYS,
    HEALTH_EMAIL_MODES,
    MAX_COVERAGE_SNAPSHOTS,
    MAX_DIGEST_CATCHUP_DAYS,
    MAX_DIGEST_EVENTS,
    MAX_DIGEST_INCIDENTS,
    MAX_FLAP_HISTORY_EVENTS,
    MAX_MINOR_SKIPPED_ROWS,
    MINOR_DEGRADATION_REASONS,
    MIN_RETAINED_ROWS_PER_SKIPPED_ROW,
    MODE_DAILY_SUMMARY,
    MODE_FAILURE_ONLY,
    MODE_OFF,
    MODE_TRANSITIONS_ONLY,
    RECOVERY_ALERT_TYPES,
    SEVERITY_HIGH,
    SEVERITY_INFO,
    SEVERITY_MEDIUM,
    SEVERITY_ORDER,
    SYSTEMIC_GROUP_DOMINANCE_PERCENT,
    SYSTEMIC_GROUP_MIN_COMPANIES,
    DigestIncident,
    HealthAlertCandidate,
    HealthAlertPolicy,
    HealthAlertResult,
    SystemicIncidentGroup,
)
from watcher.health.store import (
    HealthAlertStore,
    _candidate_from_payload,
    _coverage_snapshot_entries,
    _coverage_snapshot_value,
    _parse_datetime,
)
from watcher.health.policy import (
    _allowed_by_mode,
    _bounded_int,
    build_alert_candidates,
    build_digest_incidents,
    _candidate,
    _failure_action,
    _fallback_regressed,
    _fingerprint_token,
    github_feed_fallback_usable,
    group_systemic_incidents,
    _grouping_error_kind,
    is_minor_degradation,
    load_health_alert_policy,
    _merge_candidates,
    _recovery_state,
    repeat_flap_deferrable,
    resolve_digest_window,
    _state_diagnostic_summary,
    usable_github_fallback,
)
from watcher.health.rendering import (
    _append_bounded,
    _candidate_lines,
    _group_lines,
    render_alert_email,
    render_daily_summary,
    render_source_health_digest,
    summarize_digest_incident,
    _yes_no_unknown,
)
from watcher.health.service import (
    LOGGER,
    LOGGER,
    SMTP_HOST,
    SMTP_PORT,
    SMTP_TIMEOUT_SECONDS,
    _empty_alert_result,
    evaluate_and_send_health_alerts,
    _evaluate_immediate_alerts,
    _health_email_env,
    _maybe_send_daily_digest,
    send_health_email,
)

__all__ = [
    "ALERT_BOTH_TIERS_UNAVAILABLE",
    "ALERT_CONTINUED_FAILURE",
    "ALERT_COVERAGE_REGRESSION",
    "ALERT_DIRECT_SOURCE_DEGRADED",
    "ALERT_FEED_STALE",
    "ALERT_MINOR_DEGRADATION",
    "ALERT_MINOR_RECOVERY",
    "ALERT_NEW_FAILURE",
    "ALERT_RECOVERY",
    "ALERT_UNKNOWN_DIAGNOSTICS",
    "DEFAULT_COOLDOWN_HOURS",
    "DEFAULT_FEED_STALE_HOURS",
    "DEFAULT_HOUR_UTC",
    "DEFAULT_MODE",
    "DEGRADATION_ALERT_TYPES",
    "DIGEST_SEVERITIES",
    "DIGEST_WINDOW_HOURS",
    "DigestIncident",
    "FAILURE_ALERT_TYPES",
    "FLAP_LOOKBACK_HOURS",
    "FLAP_REPEAT_THRESHOLD",
    "GITHUB_EVIDENCE_HORIZON_DAYS",
    "HEALTH_EMAIL_MODES",
    "HealthAlertCandidate",
    "HealthAlertPolicy",
    "HealthAlertResult",
    "HealthAlertStore",
    "LOGGER",
    "LOGGER",
    "MAX_COVERAGE_SNAPSHOTS",
    "MAX_DIGEST_CATCHUP_DAYS",
    "MAX_DIGEST_EVENTS",
    "MAX_DIGEST_INCIDENTS",
    "MAX_FLAP_HISTORY_EVENTS",
    "MAX_MINOR_SKIPPED_ROWS",
    "MINOR_DEGRADATION_REASONS",
    "MIN_RETAINED_ROWS_PER_SKIPPED_ROW",
    "MODE_DAILY_SUMMARY",
    "MODE_FAILURE_ONLY",
    "MODE_OFF",
    "MODE_TRANSITIONS_ONLY",
    "RECOVERY_ALERT_TYPES",
    "SEVERITY_HIGH",
    "SEVERITY_INFO",
    "SEVERITY_MEDIUM",
    "SEVERITY_ORDER",
    "SMTP_HOST",
    "SMTP_PORT",
    "SMTP_TIMEOUT_SECONDS",
    "SYSTEMIC_GROUP_DOMINANCE_PERCENT",
    "SYSTEMIC_GROUP_MIN_COMPANIES",
    "SystemicIncidentGroup",
    "build_alert_candidates",
    "build_digest_incidents",
    "evaluate_and_send_health_alerts",
    "github_feed_fallback_usable",
    "group_systemic_incidents",
    "is_minor_degradation",
    "load_health_alert_policy",
    "render_alert_email",
    "render_daily_summary",
    "render_source_health_digest",
    "repeat_flap_deferrable",
    "resolve_digest_window",
    "send_health_email",
    "summarize_digest_incident",
    "usable_github_fallback",
]
